image:
  name: alpine/git:latest
  entrypoint: [""] # override the ["git"] entrypoint provided by alpine/git

stages:
  - push-to-remote

push-to-remote-job:
  stage: push-to-remote
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - git checkout main
    - git status
    - echo -e "* On branch"
    - echo -e "---"
    - git branch --show-ref
    - echo -e "\n* List checked out contents of github repo"
    - echo -e "---"
    - ls -la
    - echo -e "\n* Push main branch to remote repo"
    - echo -e "---"
    - "git -c http.extraheader='Authorization: Basic $REMOTE_PAT' push --force $REMOTE_URL main"