image:
  name: alpine/git:latest
  entrypoint: [""] # override the ["git"] entrypoint provided by alpine/git

stages:
  - push-to-remote

push-to-remote-job:
  stage: push-to-remote
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
#    - git fetch --unshallow origin
    - git checkout main
    - echo -e "* On branch" `git branch --show-current`
    - echo -e "\n* List checked out contents of github repo"
    - ls -la
    - echo -e "\n* Push main branch to remote repo"
    - "git -c http.extraheader=\"Authorization: Basic $REMOTE_PAT\" push --force $REMOTE_URL main"