image:
  name: alpine/git:latest
  entrypoint: [""] # override the ["git"] entrypoint provided by alpine/git

stages:
  - push-to-remote

push-to-remote-develop-job:
  stage: push-to-remote
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "feature/ingrid-harmonisierung"
  script:
    - git checkout $CI_COMMIT_BRANCH
    - git reset --hard FETCH_HEAD
    - "git -c http.extraheader=\"Authorization: Basic $REMOTE_PAT\" push --force $REMOTE_REPO_URL $CI_COMMIT_BRANCH"

push-to-remote-release-job:
  stage: push-to-remote
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - git checkout main
    - git reset --hard FETCH_HEAD
    - "git -c http.extraheader=\"Authorization: Basic $REMOTE_PAT\" push $REMOTE_REPO_URL main:release"
    - VERSION=$(git describe --tags --abbrev=0)
    - >-
      wget --header='Content-Type: application/json'
      -qO- --header="Authorization: Basic $REMOTE_PAT"
      --post-data="{ \"sourceRefName\": \"refs/heads/release\", \"targetRefName\": \"refs/heads/main\", \"title\": \"$VERSION\" }"
      $REMOTE_PULLREQUEST_URL
