image:
  name: alpine/git:latest
  entrypoint: [""] # override the ["git"] entrypoint provided by alpine/git

stages:
  - push-to-remote

# on push to main, push to ADO->temp
push-to-remote-job:
  stage: push-to-remote
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - git checkout main
    - git pull # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4587
    - "git -c http.extraheader=\"Authorization: Basic $REMOTE_PAT\" push --force $REMOTE_URL main:temp"
