version: '3'
services:

  elastic:
    image: docker-registry.wemove.com/ingrid-elasticsearch-with-decompound:6.8.4
    container_name: mcloud-elastic
    environment:
      - cluster.name=ingrid-harvester
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - network.publish_host=127.0.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/set-pw-es:/usr/share/elasticsearch/bin/set-pw-es
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - mcloudnetwork

  mcloud:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ingrid-harvester
    environment:
     - NODE_ENV=development
     - ELASTIC_URL=http://elastic:9200
     - ELASTIC_VERSION=8
     - ELASTIC_USER=elastic
     - ELASTIC_PASSWORD=
    ports:
      - 4200:4200
      - 8090:8090
    working_dir: /opt/ingrid/harvester
    command: sh entrypoint-dev.sh
    depends_on:
        - elastic
    networks:
      - mcloudnetwork

volumes:
  esdata:

networks: 
  mcloudnetwork: