version: '3'
services:

  harvester:
    build: .
    container_name: metadata-harvester
    environment:
     - NODE_ENV=production
     - ES_HOST=elastic
     - ELASTIC_URL=http://elastic:9200
     - ELASTIC_PASSWORD=elastic
    ports:
      - 8090:8090
    working_dir: /opt/mcloud/server
    command: node app/index.js
    networks:
      - metadata-network

networks:
  metadata-network: