version: '3'
services:

  harvester:
    build: .
    container_name: ingrid-harvester
    environment:
     - NODE_ENV=production
     - ES_HOST=elastic
     - ELASTIC_URL=http://elastic:9200
     - ELASTIC_PASSWORD=elastic
    ports:
      - 8090:8090
    working_dir: /opt/ingrid/harvester/server
    command: node app/index.js