version: '3'
services:

  mcloud:
    build: .
    container_name: ingrid-harvester
    environment:
     - NODE_ENV=production
     - ELASTIC_URL=http://elastic:9200
     - ELASTIC_VERSION=8
     - ELASTIC_USER=elastic
     - ELASTIC_PASSWORD=
     - IMPORTER_PROFILE=diplanung
    ports:
      - 8090:8090
    working_dir: /opt/ingrid/harvester/server
    command: node app/index.js