version: '3'
services:

  elastic:
    image: docker-registry.wemove.com/ingrid-elasticsearch-with-decompound:6.8.4
    container_name: mcloud-elastic
    environment:
      - cluster.name=mcloud
      # enabling memory_lock leads to the following error:
      # node_modules/elasticsearch/src/lib/connectors/http.js:188       response += d;
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - xpack.security.enabled=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - network.publish_host=127.0.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/set-pw-es:/usr/share/elasticsearch/bin/set-pw-es
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - mcloudnetwork

  mcloud:
    build: .
    container_name: mcloud
    environment:
     - NODE_ENV=production
     - ES_HOST=elastic
     - ELASTIC_URL=http://elastic:9200
    ports:
      - 8090:8090
    working_dir: /opt/mcloud
    command: sh entrypoint.sh
    depends_on:
        - elastic
    networks:
      - mcloudnetwork

volumes:
  esdata:

networks: 
  mcloudnetwork: