version: '3'
services:

  mcloud:
    build: .
    container_name: mcloud
    environment:
     - NODE_ENV=production
     - ES_HOST=elastic
     - ELASTIC_URL=http://elastic:9200
     - ELASTIC_PASSWORD=elastic
    ports:
      - 8090:8090
    working_dir: /opt/mcloud
    command: cd server && node app/index.js
    depends_on:
        - elastic
    networks:
      - mcloudnetwork

volumes:
  esdata:

networks: 
  mcloudnetwork: