FROM node:16.18.0-bullseye-slim

WORKDIR /opt/ingrid/harvester
COPY . ./

WORKDIR /opt/ingrid/harvester/server
RUN npm install

WORKDIR /opt/ingrid/harvester/client
RUN npm install

EXPOSE 4200 8090 9200

CMD ["tail", "-f", "/dev/null"]