services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: ingrid-elastic
    environment:
      - cluster.name=ingrid-harvester
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
      - network.publish_host=127.0.0.1
      - ELASTIC_PASSWORD=
    volumes:
      - esdata8:/usr/share/elasticsearch/data
      - ./elasticsearch/set-pw-es:/usr/share/elasticsearch/bin/set-pw-es
    restart: unless-stopped
    ports:
      - "9200:9200"
    networks:
      - ingrid-harvester-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3-amd64
    container_name: ingrid-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    networks:
      - ingrid-harvester-network

  harvester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingrid-harvester
    image: ingrid-harvester
    environment:
#     - NODE_ENV=development
     - IMPORTER_PROFILE=diplanung
     - DB_URL=postgres
     - ELASTIC_URL=http://elastic:9200
     - ELASTIC_VERSION=8
     - ELASTIC_ALIAS=harvester
     - ELASTIC_USER=elastic
     - ELASTIC_PASSWORD=
    ports:
      - "8090:8090"
    working_dir: /opt/ingrid/harvester/server
    command: node app/index.js
    networks:
      - ingrid-harvester-network

  postgres:
    image: "postgres"
    restart: unless-stopped
    container_name: postgres
    tmpfs:
      - /run
      - /var/cache
      - /pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /pgdata
    networks:
      - ingrid-harvester-network

volumes:
  esdata8:

networks:
  ingrid-harvester-network:
